apply plugin: 'com.android.application'

android {
    namespace 'com.yzx.chat'
    compileSdk 35

    defaultConfig {
        applicationId "io.zxingye.library.surfacebridge"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}


dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')

    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
    implementation 'androidx.emoji:emoji:1.1.0'
    implementation 'androidx.emoji:emoji-bundled:1.1.0'

    implementation 'com.google.android.material:material:1.12.0'
    implementation 'com.google.code.gson:gson:2.11.0'
    implementation 'com.google.zxing:core:3.3.3'


    implementation 'com.github.JessYanCoding:AndroidAutoSize:v1.2.1'
    implementation 'com.afollestad.material-dialogs:core:0.9.6.0'
    implementation 'com.amap.api:3dmap-location-search:latest.integration'
    implementation 'com.github.bumptech.glide:glide:4.9.0'
//    implementation 'me.jessyan:autosize:1.1.2'

    annotationProcessor 'com.github.bumptech.glide:compiler:4.9.0'
    annotationProcessor 'androidx.annotation:annotation:1.9.1'

    implementation 'cn.rongcloud.sdk:im_lib:5.7.5'

}
