apply plugin: 'com.android.library'

def config = rootProject.ext
android {
    compileSdk config.versions.compileSdkVersion

    defaultConfig {
        minSdk config.versions.minSdkVersion
        targetSdk config.versions.targetSdkVersion
        versionCode config.versions.versionCode
        versionName config.versions.versionName
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            res.srcDirs = ['res']
            jniLibs.srcDirs = ['libs']
        }
    }
}

dependencies {
    api fileTree(dir: 'libs', include: ['*.jar'])

}
